apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argos-wallet-ingress
  namespace: argos-wallet
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: api.argoswallet.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 80
  tls:
    - hosts:
        - api.argoswallet.dev
      secretName: argos-wallet-tls
